name: Github App Test

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'branch'
        type: string
        default: main
        required: false

jobs:
  app_authentication:
    runs-on: ubuntu-latest
    outputs:
      APP_TOKEN: ${{ steps.generate_token.outputs.token }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.LLCICD_APP_ID }}
          private_key: ${{ secrets.LLCICD_PRIVATE_KEY }}
      - name: Use the token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat

  build:
    runs-on: ubuntu-latest
    needs: [app_authentication]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.events.inputs.BRANCH }}
